name: venv
channels:
  - conda-forge
  - defaults
dependencies:
  - _tflow_select=2.2.0=eigen
  - abseil-cpp=20211102.0=hc377ac9_0
  - absl-py=1.4.0=py311hca03da5_0
  - aiohttp=3.9.0=py311h80987f9_0
  - appnope=0.1.3=pyhd8ed1ab_0
  - asttokens=2.4.1=pyhd8ed1ab_0
  - astunparse=1.6.3=py_0
  - blas=1.0=openblas
  - blinker=1.6.2=py311hca03da5_0
  - brotli=1.0.9=h1a28f6b_7
  - brotli-bin=1.0.9=h1a28f6b_7
  - brotli-python=1.0.9=py311h313beb8_7
  - bzip2=1.0.8=h93a5062_5
  - c-ares=1.19.1=h80987f9_0
  - ca-certificates=2023.12.12=hca03da5_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - certifi=2024.2.2=py311hca03da5_0
  - cffi=1.16.0=py311h80987f9_0
  - click=8.1.7=py311hca03da5_0
  - comm=0.2.1=pyhd8ed1ab_0
  - contourpy=1.2.0=py311h48ca7d4_0
  - cryptography=41.0.3=py311h3c57c4d_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.8.0=py311ha891d26_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - dill=0.3.7=py311hca03da5_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - executing=2.0.1=pyhd8ed1ab_0
  - ffmpeg=4.2.2=h04105a8_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=h1192e45_0
  - gast=0.4.0=pyhd3eb1b0_0
  - gettext=0.21.0=h13f89a0_1
  - giflib=5.2.1=h80987f9_3
  - gmp=6.2.1=hc377ac9_3
  - gmpy2=2.1.2=py311h40f64dc_0
  - gnutls=3.6.15=h887c41c_0
  - google-auth=2.22.0=py311hca03da5_0
  - google-auth-oauthlib=0.5.2=py311hca03da5_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - gpytorch=1.11=pyhd8ed1ab_0
  - grpc-cpp=1.48.2=h877324c_0
  - grpcio=1.48.2=py311h877324c_0
  - h5py=3.9.0=py311hba6ad2f_0
  - hdf5=1.12.1=h160e8cb_2
  - icu=68.1=hc377ac9_0
  - importlib-metadata=7.0.1=pyha770c72_0
  - importlib_metadata=7.0.1=hd8ed1ab_0
  - ipykernel=6.29.0=pyh3cd1d5f_0
  - ipympl=0.9.3=py311hca03da5_0
  - ipython=8.20.0=pyh707e725_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jaxtyping=0.2.25=pyhd8ed1ab_0
  - jedi=0.19.1=pyhd8ed1ab_0
  - joblib=1.2.0=py311hca03da5_0
  - jpeg=9e=h80987f9_1
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.7.1=py311h267d04e_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.4.4=py311h313beb8_0
  - krb5=1.20.1=h8380606_1
  - lame=3.100=h1a28f6b_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libbrotlicommon=1.0.9=h1a28f6b_7
  - libbrotlidec=1.0.9=h1a28f6b_7
  - libbrotlienc=1.0.9=h1a28f6b_7
  - libcurl=8.2.1=h0f1d93c_0
  - libcxx=16.0.6=h4653b0c_0
  - libdeflate=1.17=h80987f9_1
  - libedit=3.1.20230828=h80987f9_0
  - libev=4.33=h1a28f6b_1
  - libexpat=2.5.0=hb7217d7_1
  - libffi=3.4.4=hca03da5_0
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libiconv=1.16=h1a28f6b_2
  - libidn2=2.3.4=h80987f9_0
  - libjpeg-turbo=2.0.0=h1a28f6b_0
  - libnghttp2=1.52.0=h10c0552_1
  - libopenblas=0.3.21=h269037a_0
  - libopus=1.3=h1a28f6b_1
  - libpng=1.6.39=h80987f9_0
  - libprotobuf=3.20.3=h514c7bf_0
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.44.2=h091b4b1_0
  - libssh2=1.10.0=h449679c_2
  - libtasn1=4.19.0=h80987f9_0
  - libtiff=4.5.1=h313beb8_0
  - libunistring=0.9.10=h1a28f6b_0
  - libvpx=1.10.0=hc377ac9_0
  - libwebp=1.3.2=ha3663a8_0
  - libwebp-base=1.3.2=h80987f9_0
  - libxml2=2.10.4=h372ba2a_0
  - libzlib=1.2.13=h53f4e23_5
  - linear_operator=0.5.2=pyhd8ed1ab_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_0
  - markdown=3.4.1=py311hca03da5_0
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - mpc=1.1.0=h8c48613_1
  - mpfr=4.0.2=h695f6f0_1
  - mpmath=1.3.0=py311hca03da5_0
  - multidict=6.0.4=py311h80987f9_0
  - munkres=1.1.4=py_0
  - ncurses=6.4=h463b476_2
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.7.3=h84b5d62_1
  - numexpr=2.8.7=py311h6dc990b_0
  - oauthlib=3.2.2=py311hca03da5_0
  - openh264=1.8.0=h98b2900_0
  - openjpeg=2.3.0=h7a6adac_2
  - openssl=1.1.1w=h1a28f6b_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=23.3.2=pyhd8ed1ab_0
  - platformdirs=4.1.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.42=pyha770c72_0
  - psutil=5.9.8=py311h05b510d_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - pyjwt=2.4.0=py311hca03da5_0
  - pyopenssl=23.2.0=py311hca03da5_0
  - pyparsing=3.0.9=py311hca03da5_0
  - pyro-api=0.1.2=pyhd8ed1ab_0
  - pyro-ppl=1.8.6=pyhd8ed1ab_0
  - pysocks=1.7.1=py311hca03da5_0
  - python=3.11.0=hf452327_1_cpython
  - python_abi=3.11=4_cp311
  - pyyaml=6.0.1=py311h80987f9_0
  - pyzmq=25.1.2=py311h6727e71_0
  - re2=2022.04.01=hc377ac9_0
  - readline=8.2=h92ec313_1
  - requests=2.31.0=py311hca03da5_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.11.4=py311hc76d9b0_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h313beb8_1
  - sqlite=3.44.2=hf2abe2d_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - sympy=1.12=py311hca03da5_0
  - tensorboard-data-server=0.7.0=py311ha6e5c4f_0
  - tensorboard-plugin-wit=1.8.1=py311hca03da5_0
  - tensorflow=2.12.0=eigen_py311h689d69b_0
  - tensorflow-base=2.12.0=eigen_py311h0a52ebb_0
  - termcolor=2.1.0=py311hca03da5_0
  - tk=8.6.13=h5083fa2_1
  - tornado=6.3.3=py311heffc1b2_1
  - tqdm=4.65.0=py311hb6e6a13_0
  - traitlets=5.14.1=pyhd8ed1ab_0
  - typeguard=2.13.3=py311hca03da5_0
  - wcwidth=0.2.13=pyhd8ed1ab_0
  - werkzeug=2.3.8=py311hca03da5_0
  - wheel=0.35.1=pyhd3eb1b0_0
  - wrapt=1.14.1=py311h80987f9_0
  - x264=1!152.20180806=h1a28f6b_0
  - xz=5.4.5=h80987f9_0
  - yaml=0.2.5=h1a28f6b_0
  - yarl=1.9.3=py311h80987f9_0
  - zeromq=4.3.5=h965bd2d_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=h53f4e23_5
  - zstd=1.5.5=hd90d995_0
  - pip:
      - adagio==0.2.4
      - aiosignal==1.3.1
      - antlr4-python3-runtime==4.11.1
      - anyio==4.2.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bitarray==2.9.2
      - bleach==6.1.0
      - bottleneck==1.3.8
      - catboost==1.2.3
      - chainer==7.8.1
      - charset-normalizer==3.3.2
      - cloudpickle==3.0.0
      - cvxopt==1.3.2
      - dask==2024.5.2
      - defusedxml==0.7.1
      - distributed==2024.5.2
      - dm-tree==0.1.8
      - editdistance==0.8.1
      - fastjsonschema==2.19.1
      - filelock==3.13.4
      - flatbuffers==23.5.26
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fs==2.4.16
      - fsspec==2024.3.1
      - fugue==0.8.7
      - fugue-sql-antlr==0.2.0
      - gcloud==0.18.3
      - googleapis-common-protos==1.62.0
      - h11==0.14.0
      - httpcore==1.0.3
      - httplib2==0.22.0
      - httpx==0.26.0
      - huggingface-hub==0.20.3
      - idna==3.6
      - imageio==2.34.0
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - jinja2==3.1.3
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.2
      - jupyter-server==2.12.5
      - jupyter-server-terminals==0.5.2
      - jupyterlab==4.1.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.3
      - jupyterlab-widgets==3.0.10
      - keras==2.15.0
      - lazy-loader==0.3
      - libclang==16.0.6
      - locket==1.0.0
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - mistune==3.0.2
      - ml-dtypes==0.2.0
      - monai==1.3.0
      - msgpack==1.0.8
      - nbclient==0.9.0
      - nbconvert==7.16.0
      - nbformat==5.9.2
      - networkx==3.3
      - nibabel==5.2.0
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - oauth2client==4.1.3
      - opencv-contrib-python==4.9.0.80
      - overrides==7.7.0
      - packaging==24.0
      - pandas==1.4.4
      - pandocfilters==1.5.1
      - partd==1.4.2
      - patsy==0.5.6
      - pillow==10.3.0
      - plotly==5.20.0
      - prometheus-client==0.20.0
      - protobuf==5.26.1
      - pyaml==23.12.0
      - pyarrow==15.0.2
      - pyreadr==0.5.0
      - pyreadstat==1.2.6
      - python-dateutil==2.9.0.post0
      - python-graphviz==0.20.1
      - python-json-logger==2.0.7
      - pytz==2024.1
      - qpd==0.4.4
      - ray==2.23.0
      - referencing==0.34.0
      - regex==2023.12.25
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.18.0
      - rpy2==3.5.15
      - safetensors==0.4.2
      - saspy==5.6.0
      - scikit-image==0.22.0
      - scikit-learn==1.5.0
      - scikit-optimize==0.9.0
      - send2trash==1.8.2
      - setuptools==69.5.1
      - sniffio==1.3.0
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - sqlglot==23.7.0
      - statsmodels==0.14.1
      - tblib==3.0.0
      - tenacity==8.2.3
      - tensorboard==2.15.1
      - tensorboardx==2.6.2.2
      - tensorflow-estimator==2.15.0
      - tensorflow-io-gcs-filesystem==0.36.0
      - tensorflow-macos==2.15.0
      - tensorflow-metal==1.1.0
      - tensorflow-probability==0.23.0
      - terminado==0.18.0
      - threadpoolctl==3.5.0
      - tifffile==2024.2.12
      - tinycss2==1.2.1
      - tokenizers==0.15.1
      - toolz==0.12.1
      - torch==2.3.0
      - torchinfo==1.8.0
      - torchvision==0.17.2
      - torchviz==0.0.2
      - transformers==4.37.2
      - triad==0.9.6
      - tune==0.1.5
      - types-python-dateutil==2.8.19.20240106
      - typing-extensions==4.11.0
      - tzdata==2024.1
      - tzlocal==5.2
      - uri-template==1.3.0
      - urllib3==2.2.1
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - widgetsnbextension==4.0.10
      - zict==3.0.0
prefix: /Users/naji/miniconda3/envs/venv
